inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'lib/bucky/test_equipment/user_operation/user_operation_helper.rb'
    - 'spec/fixtures/**/*'
    - 'spec/test_code/**/*'
    - 'template/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.5

Metrics/AbcSize:
  Enabled: false

# Allow method prefix start with 'set_' and 'get_'
Naming/AccessorMethodName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'bucky-core.gemspec'
    - 'lib/bucky/core/database/test_data_operator.rb'
    - 'lib/bucky/core/test_core/test_class_generator.rb'

Naming/ClassVars:
  Exclude:
    - 'lib/bucky/test_equipment/selenium_handler/webdriver_handler.rb'
    - 'lib/bucky/test_equipment/test_case/abst_test_case.rb'
    - 'lib/bucky/utils/config.rb'
    - 'lib/bucky/tools/lint.rb'

Metrics/CyclomaticComplexity:
  Enabled: false

# Allow missing top-level documentation comment of class
Lint/Documentation:
  Enabled: false

Layout/FrozenStringLiteralComment:
  EnforcedStyle: always

Naming/GlobalVars:
  AllowedVariables: [$bucky_home_dir, $debug, $job_id, $round]

# Not allow using '->' for multi-line lambdas.
Naming/Lambda:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Max: 140
  Exclude:
    - 'spec/**/*.rb'

PerceivedComplexity:
  Enabled: false

Lint/UselessAssignment:
  Exclude:
    - 'lib/bucky/core/test_core/test_result.rb'

Metrics/ClassLength:
  Max: 110

Lint/UselessAccessModifier:
  Exclude:
    - 'example/**/*'
