version: '3'
services:
  bucky-core:
    container_name: bucky-core
    build:
      context: .
      dockerfile: Dockerfile.system-test
    volumes:
      - .:/bucky-core
    tty: true
    depends_on:
      chrome:
        condition: service_healthy
      web:
        condition: service_started
  chrome:
    container_name: bucky-chrome
    image: selenium/standalone-chromium:128.0
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4444 || exit 1"]
      interval: 3s
      timeout: 5s
      retries: 2
    ports:
      - '4444:4444'
      # For local debug
      - '5901:5900'
  web:
    container_name: bucky.net
    build:
      context: docker/nginx
